# Project: Advanced-Homework14
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Advanced-Homework14.o
LINKOBJ  = Advanced-Homework14.o
LIBS     = -L"C:/Users/ят/Desktop/DevCppPortable/MinGW64/lib" -L"C:/Users/ят/Desktop/DevCppPortable/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/ят/Desktop/DevCppPortable/MinGW64/include" -I"C:/Users/ят/Desktop/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/ят/Desktop/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/ят/Desktop/DevCppPortable/MinGW64/include" -I"C:/Users/ят/Desktop/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/ят/Desktop/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/ят/Desktop/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Advanced-Homework14.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

Advanced-Homework14.o: Advanced-Homework14.c
	$(CC) -c Advanced-Homework14.c -o Advanced-Homework14.o $(CFLAGS)
